### ISSUE TITLE
can't install 'scintegral' package.

### ISSUE THREAD

**Issue by Beyondvisible** [hanbin973/scIntegral#1]
Hello,
I am trying to follow the tutorial.
All the codes successfully worked, but I am struggling with 'scintegral' package installation. 
To install the package, I tried the following codes, but failed all.

> conda install scintegral
> pip  install scintegral
> pip install git+https://github.com/hanbin973/scIntegral.git
> pip install git+git://github.com/hanbin973/scIntegral.git

Sorry for this basic question!
 
From a novice at python..

**Comment by hanbin973** [comment]
I'm sorry for the late response.
Currently the package is yet on pip nor conda repository.
Therefore, you have to manually load the .py script file for each use. 
We are looking forward to upload the package to public repo in a near future.

**Comment by hanbin973** [comment]
The package was uploaded in pypi. Now it can be installed through pip. However, there were some major changes in the interface. A documentation will be released in few days.
